config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'homes#top'

  post '/articles' => 'articles#create'

  get '/articles' => 'articles#index'

  get '/articles/:id' => 'articles#show', as: 'article'

  get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'

  patch '/articles/:id' => 'articles#update', as: 'update_article'

  delete '/articles/:id' => 'articles#destroy', as: 'destroy_article'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  	@article = Article.new
  end

  def create

  	article = Article.new(articles_params)

  	article.save

  	redirect_to articles_path(article.id)
  end

  def index
  	@articles = Article.all
    @article = Article.new
  end

  def show
  	@article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
        article = Article.find(params[:id])
        article.update(articles_params)
        redirect_to article_path(article.id)
  end

  def destroy
        article = Article.find(params[:id])
        article.destroy
        redirect_to articles_path
  end

  private

  def articles_params
  	  params.require(:article).permit(:title, :body, :weather)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@article) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>
<% end %>

app/views/articles/index.html.erb
<ul class="nav nav-tabs">
	<li role="presentation" class="active"><a href="#">ホーム</a></li>
	<li role="presentation"><a href="#">メニューＡ</a></li>
	<li role="presentation"><a href="#">メニューＢ</a></li>
</ul>
<div class="container-fluid">
<div class="row">
<div class="col-md-4">

<h1>新規投稿</h1>
<%= form_for(@article) do |f| %>

    <h4> タイトル</h4>
    <%= f.text_field :title %>

    <h4>天気</h4>
    <%= f.text_area :weather %>

    <h4> 本文</h4>
    <%= f.text_area :body %>

    <%= f.submit '投稿' %>

<% end %>
</div>

<div class="col-md-8">

<h1>投稿一覧</h1>

<table width="100%">

<tr>
	<th>タイトル</th>

	<th>天気</th>

	<th>本文</th>
</tr>

<% @articles.each do |article| %>

<div class="container-fluid">
<div class="row">
	<td class="col-sm-4">
		<p><%=link_to article.title, "/articles/#{article.id}" %></p>
	</td>

	<td class="col-sm-4">
		<p><%=link_to article.weather, "/articles/#{article.id}"%></p>
	</td>

	<td class="col-sm-4">
		<p><%=link_to article.body, "/articles/#{article.id}" %></p>
	</td>

</tr>

<% end %>
</table>
</div>
</div>
</div>

app/views/articles/new.html.erb
<h1>新規投稿</h1>
<%= form_for(@article) do |f| %>

    <h4> タイトル</h4>
    <%= f.text_field :title %>

    <h4>天気</h4>
    <%= f.text_area :weather %>

    <h4> 本文</h4>
    <%= f.text_area :body %>

    <%= f.submit '投稿' %>

<% end %>

app/views/articles/show.html.erb
<h2>タイトル</h2>
<p><%= @article.title %></p>
<h2>本文</h2>
<p><%= @article.body %></p>
<h2>天気</h2>
<p><%= @article.weather %></p>
<%= link_to "編集", edit_article_path(@article.id) %>
<%= link_to "一覧ページへ戻る", articles_path %>
<%= link_to "削除", destroy_article_path(@article.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

app/views/homes/top.html.erb
<h1>Watanabe Ryouta</h1>
<%= image_tag '/assets/inu.jpg'%>
<%= link_to '新規投稿ページに行く', articles_new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RyotaDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>